# config.yaml

directories:
    content: "content"
    templates: "templates"
    output: "docs"

default_template: "base.html"

baseURL: "https://example.com"
languageCode: "en-us"

title: "My Website"
description: "This is my website"
author: "Urmila Bade"
keywords: "website, blog, portfolio"
copyright: "© Urmila Bade"

menu:
    - name: "Urmila Bade"
      url: "/"
    - name: "Projects"
      url: "/projects"
    - name: "About"
      url: "/about.html"
    - name: "Contact"
      url: "/contact.html"

social:
    twitter: "urmibade"
    github: "urmibade"
    linkedin: "urmibade"
    email: "urmibade@example.com"
