name: Build Executables

on:
  push:
    paths:
      - 'git_auto_commit.py'
      - '.github/workflows/build-executables.yml'

jobs:
  build:
    name: Build Executable
    runs-on: ${{ matrix.os }}
    permissions:
          contents: write

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build Executable
        run: |
          pyinstaller --onefile git_auto_commit.py
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv dist/git_auto_commit.exe ./git_auto_commit.exe
          else
            mv dist/git_auto_commit ./git_auto_commit
          fi

      - name: Check for changes
        id: check_changes
        run: echo "::set-output name=changes::$(git status --porcelain)"

      - name: Commit Executables to Repository
        if: steps.check_changes.outputs.changes != ''
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
          git add git_auto_commit.exe
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            git add git_auto_commit
          fi
          git commit -m "Add executable files"
          git push origin main
