name: Build Executables

on:
  push:
    paths:
      - 'git_auto_commit.py'
      - '.github/workflows/build-executables.yml'

jobs:
  build:
    name: Build Executable
    runs-on: ${{ matrix.os }}
    permissions:
          contents: write

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install PyInstaller
        run:
          pip install pyinstaller

      - name: Build Executable
        run: |
          pyinstaller --onefile git_auto_commit.py


      - name: Move Executables to Root
        run: |
          mv ./dist/git_auto_commit.exe ./git_auto_commit.exe
          mv ./dist/git_auto_commit ./git_auto_commit

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: |
            git_auto_commit.exe  # For Windows
            git_auto_commit      # For Linux
          if: matrix.os == 'ubuntu-latest' || matrix.os == 'windows-latest'

  commit:
    name: Commit Executables to Repository
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Executable Artifact
        uses: actions/download-artifact@v4
        with:
          name: executable

      - name: Check for changes
        id: check_changes
        run: echo "::set-output name=changes::$(git status --porcelain)"

      - name: Commit Executables to Repository
        if: steps.check_changes.outputs.changes != ''
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add git_auto_commit.exe git_auto_commit
          git commit -m "Add executable files"
          git push origin main
